<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="TableofContent.aspx.cs" Inherits="myWebApplication.TableofContent" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml"  manifest="TableofContent.aspx">
<head runat="server">
    <title></title>
</head>
<body style="background-color:aliceblue">
    <form id="form1" runat="server">
    <div>
        <h1>Table of Content</h1>
        <ul>
            <li><a href ="alternate.aspx" target ="_blank">Alternate.aspx</a></li>
            <p>This page consist of pagination property. The functionality was achieved by adding the event handler peopleGridView_PageIndexChanging which is 
                is void function and it handles the page index changing event when the page number at the bottom is clicked. This lacks the property of changing of 
                font color on hovering over the row while the change in background color remains intact. 
            </p>
            <li><a href ="Default.aspx" target ="_blank">Default.aspx</a></li>
            <p>This page consist of font color changing property on hovering over the row. The change in row color over mouse hovering was obtained 
                using event handler peopleGridView_RowCreated, a void function. The two function within it changes the background color of the row
                but the text color is changed by simple css code that uses "tr:hover td" tag. However this page lacks the pagination property.
                <![CDATA [<asp:BoundField DataField="emplid" HeaderText="Emplid" SortExpression="emplid" ItemStyle-Wrap ="false" />]> is removed.
            </p>
            <h2>Methods used</h2>
                <ul>
                    <ul>
                        <li>page_load()</li>
                        <p></p>
                        <li>dbResult()</li>
                        <p>Method returning table after querying the database and showed to the webpage.</p>
                        <li>Event handlers</li>
                        <ul>
                            <li>peopleGridView_Sorting</li>
                            <p>This event handler handles the sorting event on clicking of the table header.</p>
                            <li>GetSortDirection</li>
                            <p>A helper method that takes column name as input and returns back the direction for that specific column.</p>
                            <li>peopleGridView_PageIndexChanging</li>
                            <p>This event handler handles the event generated by clicking on the page number.</p>
                            <li>peopleGridView_RowCreated</li>
                            <p>This event handler handles the event generated by mouse hovering on the row of the table displayed</p>
                        </ul>
                    </ul>
                </ul>
            <li><asp:HyperLink ID="HyperLink1" runat="server" href="filtered.aspx" Target="_blank">filtered.aspx</asp:HyperLink></li>
            <p>This page has additional feature of dropdown menu. It gives access to only the field selected which is department name 
                in this case. Additonal function PopulateDropDownlist1 and the event handler DropDownlist_SelectedIndexChanged where added
                on the backend code where as the filtered.aspx was modified by addition of the UpDatePanel that wrapped up the existing code.
                Two child tags namely Trigger and Content Template were used. Trigger contained AsyncPostBackTrigger tag that would actually 
                trigger to display the table on selection of the item in drop down list. 
                Suggested change of elements inside the tag were AutoPostback = true and EventName = "selectedIndexchanged".
            </p>
            <li><asp:HyperLink ID="HyperLink2" runat="server" href="EditableSearchable.aspx" Target="_blank">EditableSearchable.aspx</asp:HyperLink></li>
            <p>
                This page contains the functionality of searching the specific data based on the data provided in the text field and on click of 
                find button. The added method is Button1_Click which is an event handler function for the click of button. There were various other 
                modification made to the sorting function as well as the Page_load function. Moreover this page is capable of showing the total number
                of result displayed on the page.  
            </p>
        </ul>
       
        

    </div>
    </form>
</body>
</html>
